---
apiVersion: v1
kind: Service
metadata:
  name: react-frontend
  namespace: {{ .Release.Namespace }}

spec:
  ports:
  - port: 3000
    targetPort: 3000
    name: http
  selector:
    app: react
    role: frontend